<?php
	require_once './../src/Numphp.php';
	use Girishk\Numphp;

	$numpy = new Numphp();

	echo "mean => ". $numpy->mean([1,2,3]) . "<br/>";
	echo "SD => ". $numpy->standardDeviation([1,2,3], true) . "<br/>";
	echo "zScore => ". $numpy->zScore(1,2,3) . "<br/>";
	echo "percentile => ". $numpy->percentile(-1.04) . "<br/>";
	echo "sten testing <br/>";
	echo "-2.01 => " . $numpy->sten(-2.01) . "<br/>";
	echo "-2 => " . $numpy->sten(-2) . "<br/>";
	echo "-1.5 => " . $numpy->sten(-1.5) . "<br/>";
	echo "-1 => " . $numpy->sten(-1) . "<br/>";
	echo "-0.5 => " . $numpy->sten(-0.5) . "<br/>";
	echo "0 => " . $numpy->sten(0) . "<br/>";
	echo "0.5 => " . $numpy->sten(0.5) . "<br/>";
	echo "1 => " . $numpy->sten(1) . "<br/>";
	echo "1.5 => " . $numpy->sten(1.5) . "<br/>";
	echo "2 => " . $numpy->sten(2) . "<br/>";
	echo "2.01 => " . $numpy->sten(2.01) . "<br/>";
	echo "-2.5 => " . $numpy->sten(-2.5) . "<br/>";
	echo "-2.001 => " . $numpy->sten(-2.001) . "<br/>";
	echo "-1.99 => " . $numpy->sten(-1.99) . "<br/>";
	echo "-1.75 => " . $numpy->sten(-1.75) . "<br/>";
	echo "-0.7 => " . $numpy->sten(-0.7) . "<br/>";
	echo "0.1 => " . $numpy->sten(0.1) . "<br/>";
	echo "0.6 => " . $numpy->sten(0.6) . "<br/>";
	echo "1.25 => " . $numpy->sten(1.25) . "<br/>";
	echo "1.55 => " . $numpy->sten(1.55) . "<br/>";
	echo "1.99 => " . $numpy->sten(1.99) . "<br/>";
	echo "2.001 => " . $numpy->sten(2.001) . "<br/>";
	echo "stanine testing <br/>";
	echo "-2.5 => " . $numpy->stanine(-2.5) . "<br/>";
	echo "-1.751 => " . $numpy->stanine(-1.751) . "<br/>";
	echo "-1.75 => " . $numpy->stanine(-1.75) . "<br/>";
	echo "-1.25 => " . $numpy->stanine(-1.25) . "<br/>";
	echo "-0.75 => " . $numpy->stanine(-0.75) . "<br/>";
	echo "-0.25 => " . $numpy->stanine(-0.25) . "<br/>";
	echo "0.25 => " . $numpy->stanine(0.25) . "<br/>";
	echo "0.75 => " . $numpy->stanine(0.75) . "<br/>";
	echo "1.25 => " . $numpy->stanine(1.25) . "<br/>";
	echo "1.75 => " . $numpy->stanine(1.75) . "<br/>";
	echo "1.7501 => " . $numpy->stanine(1.7501) . "<br/>";
	echo "2.01 => " . $numpy->stanine(2.01) . "<br/>";
	echo "2.5 => " . $numpy->stanine(2.5) . "<br/>";
	echo "-2.5 => " . $numpy->stanine(-2.5) . "<br/>";
	echo "-2 => " . $numpy->stanine(-2) . "<br/>";
	echo "-1.99 => " . $numpy->stanine(-1.99) . "<br/>";
	echo "-1.75 => " . $numpy->stanine(-1.75) . "<br/>";
	echo "-0.7 => " . $numpy->stanine(-0.7) . "<br/>";
	echo "0 => " . $numpy->stanine(0) . "<br/>";
	echo "0.5 => " . $numpy->stanine(0.5) . "<br/>";
	echo "0.75 => " . $numpy->stanine(0.75) . "<br/>";
	echo "1 => " . $numpy->stanine(1) . "<br/>";
	echo "1.5 => " . $numpy->stanine(1.5) . "<br/>";
	echo "2 => " . $numpy->stanine(2) . "<br/>";
	echo "2.01 => " . $numpy->stanine(2.01) . "<br/>";
	echo "2.5 => " . $numpy->stanine(2.5) . "<br/>";
?>
